export const AIR_POAP_MINT_TRANSACTION_LAST_UPDATED_INDEX_ID =
    "AIR_POAP_MINT_TRANSACTION_LAST_UPDATED_INDEX"
export const AIR_POAP_TRANSFER_TRANSACTION_LAST_UPDATED_INDEX_ID =
    "AIR_POAP_TRANSFER_TRANSACTION_LAST_UPDATED_INDEX"
export const AIR_POAP_EVENT_ATTENDEE_LAST_UPDATED_INDEX_ID =
    "AIR_POAP_EVENT_ATTENDEE_LAST_UPDATED_INDEX"
export const AIR_POAP_EVENT_LAST_UPDATED_INDEX_ID = "AIR_POAP_EVENT_LAST_UPDATED_INDEX"
export const AIR_POAP_ATTENDEE_LAST_UPDATED_INDEX_ID = "AIR_POAP_ATTENDEE_LAST_UPDATED_INDEX"
export const AIR_DATA_UPDATE_LAST_UPDATED_INDEX_ID = "AIR_DATA_UPDATE_LAST_UPDATED_INDEX"
export const BASE_URI = "BASE_URI"
export const POAP = "POAP"
export const MINT = "MINT"
export const TRANSFER = "TRANSFER"
