import {
  BigInt,
  ByteArray,
} from "@graphprotocol/graph-ts";

export const AIR_DOMAIN_OWNER_CHANGED_ENTITY_COUNTER_ID = "AIR_DOMAIN_OWNER_CHANGED_ENTITY_COUNTER";
export const AIR_DOMAIN_TRANSFER_ENTITY_COUNTER_ID = "AIR_DOMAIN_TRANSFER_ENTITY_COUNTER";
export const AIR_DOMAIN_NEW_RESOLVER_ENTITY_COUNTER_ID = "AIR_DOMAIN_NEW_RESOLVER_ENTITY_COUNTER";
export const AIR_DOMAIN_NEW_TTL_ENTITY_COUNTER_ID = "AIR_DOMAIN_NEW_TTL_ENTITY_COUNTER";
export const AIR_NAME_REGISTERED_ENTITY_COUNTER_ID = "AIR_NAME_REGISTERED_ENTITY_COUNTER";
export const AIR_NAME_RENEWED_ENTITY_COUNTER_ID = "AIR_NAME_RENEWED_ENTITY_COUNTER";
export const AIR_ADDR_CHANGED_ENTITY_COUNTER_ID = "AIR_ADDR_CHANGED_ENTITY_COUNTER";
export const AIR_SET_PRIMARY_DOMAIN_ENTITY_COUNTER_ID = "AIR_SET_PRIMARY_DOMAIN_ENTITY_COUNTER";

export const AIR_META_ID = "AIR_META";
export const ETHEREUM_MAINNET_ID = "1";
export const AIR_EXTRA_TTL = 'ttl';

export const ROOT_NODE = '0x0000000000000000000000000000000000000000000000000000000000000000'
export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";